modLoader="javafml"
loaderVersion="[1,)"
license="${mod_license}"
issueTrackerURL="https://github.com/FunctionHookTJU/old_wu_java-template-26.2/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="FunctionHookTJU"
displayURL="https://github.com/FunctionHookTJU/old_wu_java-template-26.2"
logoFile="old_wu_java/icon.png"
description='''
Old Wu Java, ported from the upstream Fabric 26.2 project to Minecraft 1.21.1 NeoForge.
'''

[[mixins]]
config="old_wu_java.mixins.json"

[[mixins]]
config="old_wu_java.client.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
